import { Profile } from "../pages/student/profile/type";

export const initialProfileData: Profile = {
  name: "",
  year: 0,
  email: "",
  bio: "",
  following: 0,
  followers: 0,
  programming_skills: [],
  language_skills: [],
  achievements: [],
  posts: [],
  projects: [],
  courses: [],
  badges: [],
  pinned: [],
  portfolio: "",
  currentFocus: "",
  departure: "",
  certifications: [],
  interests_hobby: [],
  socialLinks: {
    facebook: "",
    instagram: "",
    youtube: "",
    github: "",
  },
  type: "",
  joinedDate: "",
};
